# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - appzur333

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /p:DeployOnBuild=true /p:OutputPath=${{ github.workspace }}/published

      - name: Debug Output Path
        run: dir ${{ github.workspace }}/published  # ตรวจสอบว่าไฟล์ถูกสร้างใน path ที่ถูกต้อง

      - name: Create Zip Package
        run: |
          Compress-Archive -Path ${{ github.workspace }}/published/* -DestinationPath ${{ github.workspace }}/published.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ${{ github.workspace }}/published.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4865581AB0E54AA2BD1C605D28534BE2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2073C0817E7F45F093E73294C1CDB88B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8D4E41404EAD44B7A8BA243F64B974B0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appzur333'
          slot-name: 'Production'
          package: ${{ github.workspace }}/published.zip

          
